[database]
name = "gis"
user = "postgres"
password = "wtz2trln"
host = "127.0.0.1"
port = "5432"

[algorithm]
name = "ch"
base_graph_table = "czedges"
mode = "static_profile"
[algorithm.parameters]
hop_count = 5
edge_difference = 190
deleted_neighbours = 120
space_size = 0

[preferences]
base_index = "length"
base_index_table = "czedges_length_index"

# [[preferences.indices]]
# name = "green"
# table_name = "czedges_green_index"
# importance = [ 0.0, -0.30, -0.60, -1.0 ]
# [[preferences.indices]]
# name = "peak"
# table_name = "czedges_peak_index"
# importance = [ 0.0, 0.5, 1.0 ]
[[preferences.indices]]
name = "road_type"
table_name = "czedges_road_type_index"
importance = [ 0.0, 0.5, 1.0 ]

