[database]
name = "gis"
user = "postgres"
password = "wtz2trln"
host = "127.0.0.1"
port = "5432"

[algorithm]
name = "dijkstra"
base_graph_table = "czedges"
mode = "dynamic_profile"

[preferences]
base_index = "length"
base_index_table = "czedges_length_index"

[[preferences.indices]]
name = "green"
table_name = "czedges_green_index"
importance = [ 0.0, -0.2, -0.4, -0.6, -0.8, -1.0 ]
[[preferences.indices]]
name = "peak"
table_name = "czedges_peak_index"
importance = [ 0.0, 0.2, 0.4, 0.6, 0.8, 1.0 ]
[[preferences.indices]]
name = "road_type"
table_name = "czedges_road_type_index"
importance = [ 0.0, 0.2, 0.4, 0.6, 0.8, 1.0 ]