[database]
name = "gis"
user = "postgres"
password = "wtz2trln"
host = "127.0.0.1"
port = "5432"

[algorithm]
# name = "ch"
name = "dijkstra"
base_graph_table = "czedges"
mode = "dynamic_profile"
# mode = "static_profile"
[algorithm.parameters]
hop_count = 5
edge_difference = 190
deleted_neighbours = 120
space_size = 0

[[profile_properties]]
name = "length"
table_name = "czedges_length_index"
importance = [ 100 ]
[[profile_properties]]
name = "green"
table_name = "czedges_green_index"
importance = [ 20, 40, 60, 80, 100 ]
[[profile_properties]]
name = "peak"
table_name = "czedges_peak_index"
importance = [ 20, 40, 60, 80, 100 ]
